# -*- coding: utf-8 -*-

# Created: Sun Feb 19 11:06:09 2017
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(815, 590)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(90, 10, 441, 551))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 30, 261, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.pushButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton.setCheckable(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setGeometry(QtCore.QRect(140, 20, 89, 16))
        self.radioButton.setShortcut("")
        self.radioButton.setCheckable(False)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setGeometry(QtCore.QRect(140, 50, 89, 16))
        self.radioButton_2.setCheckable(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(310, 30, 121, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 20, 89, 16))
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_4.setGeometry(QtCore.QRect(10, 50, 89, 16))
        self.radioButton_4.setObjectName("radioButton_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 130, 421, 401))
        self.groupBox_4.setObjectName("groupBox_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 20, 61, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setGeometry(QtCore.QRect(110, 20, 71, 20))
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 20, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.line = QtWidgets.QFrame(self.groupBox_4)
        self.line.setGeometry(QtCore.QRect(20, 43, 391, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 70, 171, 121))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 42, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 72, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 72, 12))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 60, 12))
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit.setGeometry(QtCore.QRect(100, 20, 61, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_3.setGeometry(QtCore.QRect(0, 0, 133, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_4.setGeometry(QtCore.QRect(100, 80, 61, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_5.setGeometry(QtCore.QRect(100, 110, 61, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_6.setGeometry(QtCore.QRect(209, 70, 201, 121))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setGeometry(QtCore.QRect(13, 20, 101, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_6)
        self.label_7.setGeometry(QtCore.QRect(20, 50, 54, 12))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_6)
        self.label_8.setGeometry(QtCore.QRect(13, 70, 101, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setGeometry(QtCore.QRect(13, 100, 131, 20))
        self.label_9.setObjectName("label_9")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_6.setGeometry(QtCore.QRect(130, 10, 61, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_7.setGeometry(QtCore.QRect(120, 40, 61, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_8.setGeometry(QtCore.QRect(120, 70, 61, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_9.setGeometry(QtCore.QRect(140, 100, 61, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 199, 171, 91))
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        self.label_10.setGeometry(QtCore.QRect(13, 30, 81, 20))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_7)
        self.label_11.setGeometry(QtCore.QRect(13, 50, 81, 20))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_7)
        self.label_12.setGeometry(QtCore.QRect(13, 70, 101, 20))
        self.label_12.setObjectName("label_12")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_10.setGeometry(QtCore.QRect(110, 20, 61, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_11.setGeometry(QtCore.QRect(110, 50, 61, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_12.setGeometry(QtCore.QRect(110, 70, 61, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_8.setGeometry(QtCore.QRect(229, 200, 181, 91))
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_13 = QtWidgets.QLabel(self.groupBox_8)
        self.label_13.setGeometry(QtCore.QRect(13, 20, 121, 20))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_8)
        self.label_14.setGeometry(QtCore.QRect(13, 40, 101, 20))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_8)
        self.label_15.setGeometry(QtCore.QRect(3, 70, 101, 20))
        self.label_15.setObjectName("label_15")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_13.setGeometry(QtCore.QRect(130, 30, 61, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_14.setGeometry(QtCore.QRect(120, 50, 61, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_15.setGeometry(QtCore.QRect(110, 70, 61, 20))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 310, 401, 80))
        self.groupBox_9.setObjectName("groupBox_9")
        self.label_16 = QtWidgets.QLabel(self.groupBox_9)
        self.label_16.setGeometry(QtCore.QRect(13, 40, 91, 20))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_9)
        self.label_17.setGeometry(QtCore.QRect(180, 40, 111, 20))
        self.label_17.setObjectName("label_17")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_16.setGeometry(QtCore.QRect(110, 50, 61, 20))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_17.setGeometry(QtCore.QRect(310, 40, 61, 20))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.groupBox_10 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_10.setGeometry(QtCore.QRect(539, 10, 261, 461))
        self.groupBox_10.setObjectName("groupBox_10")
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_11.setGeometry(QtCore.QRect(30, 20, 231, 231))
        self.groupBox_11.setObjectName("groupBox_11")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_11)
        self.tableWidget.setGeometry(QtCore.QRect(10, 21, 211, 211))
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setLineWidth(0)
        self.tableWidget.setRowCount(22)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(85)
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_12.setGeometry(QtCore.QRect(9, 269, 241, 181))
        self.groupBox_12.setObjectName("groupBox_12")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.groupBox_12)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 30, 231, 161))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.tableWidget_2.horizontalHeader().setVisible(True)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(60)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(5)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(22)
        self.groupBox_13 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_13.setGeometry(QtCore.QRect(539, 479, 161, 81))
        self.groupBox_13.setObjectName("groupBox_13")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 30, 71, 23))
        self.pushButton_4.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_4.setAutoDefault(False)
        self.pushButton_4.setDefault(False)
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_5.setGeometry(QtCore.QRect(80, 30, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.groupBox_14 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_14.setGeometry(QtCore.QRect(709, 479, 91, 81))
        self.groupBox_14.setObjectName("groupBox_14")
        self.lcdNumber = QtWidgets.QLCDNumber(self.groupBox_14)
        self.lcdNumber.setGeometry(QtCore.QRect(10, 40, 64, 23))
        self.lcdNumber.setObjectName("lcdNumber")
        self.toolBox = QtWidgets.QToolBox(self.centralWidget)
        self.toolBox.setGeometry(QtCore.QRect(0, 0, 81, 561))
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 81, 457))
        self.page.setObjectName("page")
        self.pushButton_6 = QtWidgets.QPushButton(self.page)
        self.pushButton_6.setGeometry(QtCore.QRect(0, 0, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.toolBox.addItem(self.page, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 81, 457))
        self.page_4.setObjectName("page_4")
        self.toolBox.addItem(self.page_4, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 81, 457))
        self.page_3.setObjectName("page_3")
        self.toolBox.addItem(self.page_3, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 81, 457))
        self.page_2.setObjectName("page_2")
        self.toolBox.addItem(self.page_2, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 815, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "请由左到右，由上到下逐行选择及输入"))
        self.groupBox_2.setTitle(_translate("MainWindow", "钻井液流型选择"))
        self.pushButton.setText(_translate("MainWindow", "用户指定"))
        self.pushButton_2.setText(_translate("MainWindow", "∅值确定"))
        self.radioButton.setText(_translate("MainWindow", "宾汉流体"))
        self.radioButton_2.setText(_translate("MainWindow", "幂律流体"))
        self.groupBox_3.setTitle(_translate("MainWindow", "计算目的选择"))
        self.radioButton_3.setText(_translate("MainWindow", "排量校核"))
        self.radioButton_4.setText(_translate("MainWindow", "排量设计"))
        self.groupBox_4.setTitle(_translate("MainWindow", "请输入参数"))
        self.label.setText(_translate("MainWindow", "井斜角(°)"))
        self.pushButton_3.setText(_translate("MainWindow", "确定"))
        self.groupBox_5.setTitle(_translate("MainWindow", "①井眼几何参数"))
        self.label_2.setText(_translate("MainWindow", "井深(m)"))
        self.label_3.setText(_translate("MainWindow", "环空外径(mm)"))
        self.label_4.setText(_translate("MainWindow", "环空内径(mm)"))
        self.label_5.setText(_translate("MainWindow", "偏心距(mm)"))
        self.groupBox_6.setTitle(_translate("MainWindow", "②钻井液性能参数"))
        self.label_6.setText(_translate("MainWindow", "钻井液密度(g/cm)"))
        self.label_7.setText(_translate("MainWindow", "流性指数"))
        self.label_8.setText(_translate("MainWindow", "稠度系数(Pa*s*n)"))
        self.label_9.setText(_translate("MainWindow", "钻井液临界固相含量(%)"))
        self.groupBox_7.setTitle(_translate("MainWindow", "③钻进参数"))
        self.label_10.setText(_translate("MainWindow", "机械钻速(m/h)"))
        self.label_11.setText(_translate("MainWindow", "钻柱钻速(rpm)"))
        self.label_12.setText(_translate("MainWindow", "机械井流量(L/min)"))
        self.groupBox_8.setTitle(_translate("MainWindow", "④岩屑参数"))
        self.label_13.setText(_translate("MainWindow", "岩屑颗粒密度(g/cm3)"))
        self.label_14.setText(_translate("MainWindow", "岩屑颗粒粒径(mm)"))
        self.label_15.setText(_translate("MainWindow", "床内岩屑浓度(%)"))
        self.groupBox_9.setTitle(_translate("MainWindow", "⑤岩屑床参数"))
        self.label_16.setText(_translate("MainWindow", "油井粒孔隙度(%)"))
        self.label_17.setText(_translate("MainWindow", "床与井壁间摩擦系数"))
        self.groupBox_10.setTitle(_translate("MainWindow", "计算数据及结果"))
        self.groupBox_11.setTitle(_translate("MainWindow", "设计边界条件"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "边界参数"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "边界参数数值"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "       井深(m)"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "      井斜角(°）"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "  环空外径(mm)"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "  环空内径(mm)"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "钻井液密度(g/cm3)"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("MainWindow", "流性指数"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("MainWindow", "稠度系数(Pa.s^n)"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("MainWindow", "岩屑颗粒粒径(mm)"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("MainWindow", "   偏心距(mm)"))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("MainWindow", "固相临界含量(%)"))
        item = self.tableWidget.item(10, 0)
        item.setText(_translate("MainWindow", "机械钻速(m/h)"))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("MainWindow", "钻柱钻速(m/h)"))
        item = self.tableWidget.item(12, 0)
        item.setText(_translate("MainWindow", "岩屑颗粒密度(g/cm3)"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_12.setTitle(_translate("MainWindow", "设计计算结果"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "临界环空返速(m/s)"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "临界排量(L/min)"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "制动环空返速(m/s)"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "制动缓控排量(L/min)"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "临界岩屑床厚度(mm)"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "计算指标"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "临界值"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "备注"))
        self.groupBox_13.setTitle(_translate("MainWindow", "进程命令"))
        self.pushButton_4.setText(_translate("MainWindow", "计算"))
        self.pushButton_5.setText(_translate("MainWindow", "退出"))
        self.groupBox_14.setTitle(_translate("MainWindow", "安全判断"))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", " 井基础数据"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", " 设计与校核"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "影 响 规 律"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "井 段 计 算"))

import 123_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

