# -*- coding: utf-8 -*-

# Created: Mon Mar 27 20:28:12 2017
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(766, 371)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit.setGeometry(QtCore.QRect(-140, 120, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 10, 621, 20))
        self.lineEdit_2.setMaxLength(15)
        self.lineEdit_2.setFrame(False)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 40, 361, 51))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 321, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_4 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout.addWidget(self.radioButton_4)
        self.radioButton_3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout.addWidget(self.radioButton_3)
        self.radioButton_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(390, 40, 311, 51))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, -1, 239, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_7 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton_7.setObjectName("radioButton_7")
        self.horizontalLayout_2.addWidget(self.radioButton_7)
        self.radioButton_6 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout_2.addWidget(self.radioButton_6)
        self.radioButton_5 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout_2.addWidget(self.radioButton_5)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 100, 191, 41))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(9, -1, 161, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_3.addWidget(self.checkBox_2)
        self.checkBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_3.addWidget(self.checkBox)
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setGeometry(QtCore.QRect(220, 100, 51, 41))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.centralWidget)
        self.frame_2.setGeometry(QtCore.QRect(300, 100, 51, 41))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(88, 150, 239, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_12 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 0, 2, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 1, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 0, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 1, 0, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout.addWidget(self.pushButton_17, 1, 2, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 0, 1, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout.addWidget(self.pushButton_19, 3, 2, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 4, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 2, 0, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout.addWidget(self.pushButton_18, 2, 2, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout.addWidget(self.pushButton_20, 4, 2, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 2, 1, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 4, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 3, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 3, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 150, 77, 171))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_24 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout_2.addWidget(self.pushButton_24, 4, 0, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout_2.addWidget(self.pushButton_23, 3, 0, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout_2.addWidget(self.pushButton_25, 5, 0, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout_2.addWidget(self.pushButton_21, 2, 0, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_2.addWidget(self.pushButton_22, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(450, 100, 71, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(True)
        self.pushButton.setDefault(True)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_2.setGeometry(QtCore.QRect(530, 100, 61, 41))
        self.pushButton_2.setDefault(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_3.setGeometry(QtCore.QRect(600, 100, 61, 41))
        self.pushButton_3.setDefault(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(420, 150, 482, 171))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_35 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_35.setObjectName("pushButton_35")
        self.gridLayout_3.addWidget(self.pushButton_35, 0, 5, 1, 1)
        self.pushButton_34 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_34.setObjectName("pushButton_34")
        self.gridLayout_3.addWidget(self.pushButton_34, 0, 4, 1, 1)
        self.pushButton_36 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_36.setObjectName("pushButton_36")
        self.gridLayout_3.addWidget(self.pushButton_36, 3, 1, 1, 1)
        self.pushButton_38 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_38.setObjectName("pushButton_38")
        self.gridLayout_3.addWidget(self.pushButton_38, 1, 2, 1, 1)
        self.pushButton_37 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_37.setObjectName("pushButton_37")
        self.gridLayout_3.addWidget(self.pushButton_37, 4, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 0, 2, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout_3.addWidget(self.pushButton_26, 0, 0, 1, 1)
        self.pushButton_32 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_32.setObjectName("pushButton_32")
        self.gridLayout_3.addWidget(self.pushButton_32, 0, 3, 1, 1)
        self.pushButton_33 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_33.setObjectName("pushButton_33")
        self.gridLayout_3.addWidget(self.pushButton_33, 2, 1, 1, 1)
        self.pushButton_29 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_29.setObjectName("pushButton_29")
        self.gridLayout_3.addWidget(self.pushButton_29, 2, 0, 1, 1)
        self.pushButton_31 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_31.setObjectName("pushButton_31")
        self.gridLayout_3.addWidget(self.pushButton_31, 1, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_3.addWidget(self.pushButton_5, 0, 1, 1, 1)
        self.pushButton_30 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_30.setObjectName("pushButton_30")
        self.gridLayout_3.addWidget(self.pushButton_30, 4, 0, 1, 1)
        self.pushButton_27 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_27.setObjectName("pushButton_27")
        self.gridLayout_3.addWidget(self.pushButton_27, 3, 0, 1, 1)
        self.pushButton_28 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_28.setEnabled(True)
        self.pushButton_28.setObjectName("pushButton_28")
        self.gridLayout_3.addWidget(self.pushButton_28, 1, 0, 1, 1)
        self.pushButton_39 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_39.setObjectName("pushButton_39")
        self.gridLayout_3.addWidget(self.pushButton_39, 2, 2, 1, 1)
        self.pushButton_40 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_40.setObjectName("pushButton_40")
        self.gridLayout_3.addWidget(self.pushButton_40, 3, 2, 1, 1)
        self.pushButton_41 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_41.setObjectName("pushButton_41")
        self.gridLayout_3.addWidget(self.pushButton_41, 4, 2, 1, 1)
        self.pushButton_42 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_42.setObjectName("pushButton_42")
        self.gridLayout_3.addWidget(self.pushButton_42, 1, 3, 1, 1)
        self.pushButton_43 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_43.setObjectName("pushButton_43")
        self.gridLayout_3.addWidget(self.pushButton_43, 2, 3, 1, 1)
        self.pushButton_44 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_44.setObjectName("pushButton_44")
        self.gridLayout_3.addWidget(self.pushButton_44, 3, 3, 1, 1)
        self.pushButton_45 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_45.setObjectName("pushButton_45")
        self.gridLayout_3.addWidget(self.pushButton_45, 4, 3, 1, 1)
        self.pushButton_46 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_46.setObjectName("pushButton_46")
        self.gridLayout_3.addWidget(self.pushButton_46, 1, 4, 1, 1)
        self.pushButton_47 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_47.setObjectName("pushButton_47")
        self.gridLayout_3.addWidget(self.pushButton_47, 2, 4, 1, 1)
        self.pushButton_48 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_48.setObjectName("pushButton_48")
        self.gridLayout_3.addWidget(self.pushButton_48, 3, 4, 1, 1)
        self.pushButton_49 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_49.setObjectName("pushButton_49")
        self.gridLayout_3.addWidget(self.pushButton_49, 4, 4, 1, 1)
        self.pushButton_50 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_50.setObjectName("pushButton_50")
        self.gridLayout_3.addWidget(self.pushButton_50, 1, 5, 1, 1)
        self.pushButton_51 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_51.setObjectName("pushButton_51")
        self.gridLayout_3.addWidget(self.pushButton_51, 2, 5, 1, 1)
        self.pushButton_52 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_52.setObjectName("pushButton_52")
        self.gridLayout_3.addWidget(self.pushButton_52, 3, 5, 1, 1)
        self.pushButton_53 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_53.setObjectName("pushButton_53")
        self.gridLayout_3.addWidget(self.pushButton_53, 4, 5, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(300, 150, 77, 171))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_55 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_55.setObjectName("pushButton_55")
        self.gridLayout_4.addWidget(self.pushButton_55, 3, 0, 1, 1)
        self.pushButton_54 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_54.setObjectName("pushButton_54")
        self.gridLayout_4.addWidget(self.pushButton_54, 4, 0, 1, 1)
        self.pushButton_57 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_57.setObjectName("pushButton_57")
        self.gridLayout_4.addWidget(self.pushButton_57, 2, 0, 1, 1)
        self.pushButton_56 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_56.setObjectName("pushButton_56")
        self.gridLayout_4.addWidget(self.pushButton_56, 0, 0, 1, 1)
        self.pushButton_58 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_58.setObjectName("pushButton_58")
        self.gridLayout_4.addWidget(self.pushButton_58, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 766, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.menu.setFont(font)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menuBar)
        self.action111 = QtWidgets.QAction(MainWindow)
        self.action111.setObjectName("action111")
        self.menu.addAction(self.action111)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_2.setText(_translate("MainWindow", "0."))
        self.radioButton_4.setText(_translate("MainWindow", "十六进制"))
        self.radioButton_3.setText(_translate("MainWindow", "十进制"))
        self.radioButton_2.setText(_translate("MainWindow", "八进制"))
        self.radioButton.setText(_translate("MainWindow", "二进制"))
        self.radioButton_7.setText(_translate("MainWindow", "角度"))
        self.radioButton_6.setText(_translate("MainWindow", "弧度"))
        self.radioButton_5.setText(_translate("MainWindow", "梯度"))
        self.checkBox_2.setText(_translate("MainWindow", "Inv"))
        self.checkBox.setText(_translate("MainWindow", "Hyp"))
        self.pushButton_12.setText(_translate("MainWindow", "）"))
        self.pushButton_10.setText(_translate("MainWindow", "Exp"))
        self.pushButton_7.setText(_translate("MainWindow", "F-E"))
        self.pushButton_9.setText(_translate("MainWindow", "dms"))
        self.pushButton_17.setText(_translate("MainWindow", "ln"))
        self.pushButton_11.setText(_translate("MainWindow", "("))
        self.pushButton_19.setText(_translate("MainWindow", "n!"))
        self.pushButton_14.setText(_translate("MainWindow", "tan"))
        self.pushButton_13.setText(_translate("MainWindow", "sin"))
        self.pushButton_18.setText(_translate("MainWindow", "log"))
        self.pushButton_20.setText(_translate("MainWindow", "1/x"))
        self.pushButton_15.setText(_translate("MainWindow", "x^y"))
        self.pushButton_16.setText(_translate("MainWindow", "x^2"))
        self.pushButton_8.setText(_translate("MainWindow", "cos"))
        self.pushButton_6.setText(_translate("MainWindow", "x^3"))
        self.pushButton_24.setText(_translate("MainWindow", "s"))
        self.pushButton_23.setText(_translate("MainWindow", "Sum"))
        self.pushButton_25.setText(_translate("MainWindow", "Dat"))
        self.pushButton_21.setText(_translate("MainWindow", "Ave"))
        self.pushButton_22.setText(_translate("MainWindow", "Sta"))
        self.pushButton.setText(_translate("MainWindow", "BackSpace"))
        self.pushButton_2.setText(_translate("MainWindow", "CE"))
        self.pushButton_3.setText(_translate("MainWindow", "C"))
        self.pushButton_35.setText(_translate("MainWindow", "And"))
        self.pushButton_34.setText(_translate("MainWindow", "Mod"))
        self.pushButton_36.setText(_translate("MainWindow", "+/-"))
        self.pushButton_38.setText(_translate("MainWindow", "6"))
        self.pushButton_37.setText(_translate("MainWindow", "B"))
        self.pushButton_4.setText(_translate("MainWindow", "9"))
        self.pushButton_26.setText(_translate("MainWindow", "7"))
        self.pushButton_32.setText(_translate("MainWindow", "/"))
        self.pushButton_33.setText(_translate("MainWindow", "2"))
        self.pushButton_29.setText(_translate("MainWindow", "1"))
        self.pushButton_31.setText(_translate("MainWindow", "5"))
        self.pushButton_5.setText(_translate("MainWindow", "8"))
        self.pushButton_30.setText(_translate("MainWindow", "A"))
        self.pushButton_27.setText(_translate("MainWindow", "0"))
        self.pushButton_28.setText(_translate("MainWindow", "4"))
        self.pushButton_39.setText(_translate("MainWindow", "3"))
        self.pushButton_40.setText(_translate("MainWindow", "."))
        self.pushButton_41.setText(_translate("MainWindow", "C"))
        self.pushButton_42.setText(_translate("MainWindow", "*"))
        self.pushButton_43.setText(_translate("MainWindow", "-"))
        self.pushButton_44.setText(_translate("MainWindow", "+"))
        self.pushButton_45.setText(_translate("MainWindow", "D"))
        self.pushButton_46.setText(_translate("MainWindow", "Or"))
        self.pushButton_47.setText(_translate("MainWindow", "Lsh"))
        self.pushButton_48.setText(_translate("MainWindow", "="))
        self.pushButton_49.setText(_translate("MainWindow", "E"))
        self.pushButton_50.setText(_translate("MainWindow", "Xor"))
        self.pushButton_51.setText(_translate("MainWindow", "Not"))
        self.pushButton_52.setText(_translate("MainWindow", "Int"))
        self.pushButton_53.setText(_translate("MainWindow", "F"))
        self.pushButton_55.setText(_translate("MainWindow", "M+"))
        self.pushButton_54.setText(_translate("MainWindow", "pi"))
        self.pushButton_57.setText(_translate("MainWindow", "MS"))
        self.pushButton_56.setText(_translate("MainWindow", "MC"))
        self.pushButton_58.setText(_translate("MainWindow", "MR"))
        self.menu.setTitle(_translate("MainWindow", "编辑"))
        self.menu_2.setTitle(_translate("MainWindow", "查看"))
        self.action111.setText(_translate("MainWindow", "111"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

